apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-rest
  template:
    metadata:
      labels:
        app: spring-rest
    spec:
      containers:
      - name: spring-rest
        image: spring-rest:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          protocol: TCP

